sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t barwieleba/lab8 -f Dockerfile.dev1 .

script:
  - docker run -e CI=true barwieleba/lab8 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Wielebareact"
  env: "Wielebareact-env
  bucket_name: "elasticbeanstalk-us-east-2-039699603980"
  bucket_path: "Wielebareact"
  edge: true
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
