sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -t barwieleba/lab8 -f Dockerfile.dev1 .

#script:
#  - docker run -e CI=true barwieleba/lab8 npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Wieleba_React"
  env: "Wielebareact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-592175577642"
  bucket_path: "Wieleba_React"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
